# SPDX-License-Identifier: Apache-2.0
# Stop the private tunnel if its required firewall service is stopped.
[Unit]
BindsTo=ficc-private-network-firewall.service
After=ficc-private-network-firewall.service
