[build-system]
requires = ["setuptools==84.0.0", "wheel==0.48.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ficc-data-mysql"
version = "0.2.5"
readme = "README.md"
description = "FICC mysql data runtime provider."
requires-python = ">=3.12"
license = "Apache-2.0"
license-files = ["LICENSE"]
dependencies = ["PyMySQL==1.1.2", "cryptography==50.0.2"]

[project.entry-points."ficc.data"]
mysql = "ficc_data_mysql"

[tool.setuptools.packages.find]
where = ["src"]
