# SPDX-License-Identifier: Apache-2.0
"""Store local startup settings and render service and desktop files."""

import json
import os
import re
import stat
import tempfile
from dataclasses import asdict, dataclass
from pathlib import Path

from .settings import Settings, private_directory

MARKER = "# Generated by FICC launcher.\n"
NAME = re.compile(r"ficc(?:-[a-z0-9][a-z0-9-]{0,40})?\Z")


def config_path() -> Path:
    return Path(os.environ.get("XDG_CONFIG_HOME", str(Path.home() / ".config"))) / "ficc/launcher.json"


def clean_text(value: str) -> str:
    if not value or any(ord(char) < 32 or ord(char) == 127 for char in value):
        raise ValueError("Startup paths must not contain control characters.")
    return value


def absolute(value: str) -> str:
    clean_text(value)
    if not Path(value).is_absolute():
        raise ValueError("Startup paths must be absolute.")
    return value


@dataclass
class LaunchConfig:
    executable: str
    state_dir: str
    unit_path: str
    desktop_path: str
    port: int = 8170
    profiles: tuple[str, ...] = ()
    ssh_config: str | None = None
    demo: bool = False

    def __post_init__(self):
        if (type(self.port) is not int or type(self.demo) is not bool
                or not isinstance(self.profiles, (tuple, list))
                or any(not isinstance(profile, str) for profile in self.profiles)):
            raise ValueError("The launcher configuration fields are invalid.")
        for value in (self.executable, self.state_dir, self.unit_path, self.desktop_path):
            absolute(value)
        if "=" in self.executable:
            raise ValueError("The executable path must not contain an equals sign.")
        if not NAME.fullmatch(Path(self.unit_path).stem) or not self.unit_path.endswith(".service"):
            raise ValueError("The service name is invalid.")
        if self.ssh_config is not None:
            absolute(self.ssh_config)
        self.profiles = tuple(self.profiles)
        Settings(state_dir=Path(self.state_dir), port=self.port, profiles=self.profiles,
                 ssh_config=Path(self.ssh_config) if self.ssh_config else None, demo=self.demo)

    @property
    def unit(self) -> str:
        return Path(self.unit_path).name

    def command(self) -> list[str]:
        result = [self.executable, "serve", "--state-dir", self.state_dir, "--port", str(self.port)]
        for profile in self.profiles:
            result.extend(["--profile", profile])
        if self.ssh_config:
            result.extend(["--ssh-config", self.ssh_config])
        if self.demo:
            result.append("--demo")
        return result


def read_private(path: Path) -> str:
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK)
    try:
        info = os.fstat(fd)
        if not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid() or info.st_mode & 0o077:
            raise ValueError("The launcher configuration must be a private regular file.")
        if info.st_size > 16384:
            raise ValueError("The launcher configuration exceeds the size limit.")
        return os.read(fd, 16385).decode()
    finally:
        os.close(fd)


def load(path: Path) -> LaunchConfig:
    private_directory(path.parent)
    value = json.loads(read_private(path))
    if not isinstance(value, dict) or value.pop("version", None) != 1:
        raise ValueError("The launcher configuration version is unsupported.")
    try:
        return LaunchConfig(**value)
    except TypeError:
        raise ValueError("The launcher configuration fields are invalid.") from None


def save(path: Path, config: LaunchConfig) -> None:
    private_directory(path.parent)
    write_file(path, json.dumps({"version": 1, **asdict(config)}, indent=2) + "\n")


def write_file(path: Path, content: str, mode: int = 0o600) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    info = path.parent.lstat()
    if not stat.S_ISDIR(info.st_mode) or info.st_uid != os.getuid() or info.st_mode & 0o022:
        raise ValueError("The startup file directory is not safe to use.")
    if path.exists() or path.is_symlink():
        info = path.lstat()
        if not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid():
            raise ValueError("The startup file is not an owned regular file.")
    fd, temporary = tempfile.mkstemp(prefix=".ficc-", dir=path.parent)
    try:
        with os.fdopen(fd, "w") as stream:
            os.fchmod(stream.fileno(), mode)
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
        directory = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(directory)
        finally:
            os.close(directory)
    finally:
        Path(temporary).unlink(missing_ok=True)


def unit_quote(value: str) -> str:
    value = clean_text(value).replace("\\", "\\\\").replace('"', '\\"')
    return '"' + value.replace("%", "%%").replace("$", "$$") + '"'


def desktop_quote(value: str) -> str:
    clean_text(value)
    escaped = "".join("\\" + char if char in '\\"`$' else char for char in value)
    return '"' + escaped.replace("\\", "\\\\").replace("%", "%%") + '"'


def unit_text(config: LaunchConfig, path: Path) -> str:
    return (MARKER + "# Configuration: " + clean_text(str(path)) + "\n"
            "[Unit]\nDescription=Federated Industrial Cluster Commander\nAfter=network.target\n\n"
            "[Service]\nType=exec\nExecStart=/usr/bin/env -- " + " ".join(map(unit_quote, config.command())) + "\n"
            "Restart=on-failure\nRestartSec=5\nTimeoutStopSec=20\nUMask=0077\n"
            "NoNewPrivileges=true\nPrivateTmp=true\n\n[Install]\nWantedBy=default.target\n")


def desktop_text(config: LaunchConfig, path: Path) -> str:
    command = [config.executable, "launch", "--launcher-config", str(path)]
    icon = clean_text(str(path.with_suffix(".svg"))).replace("\\", "\\\\")
    return (MARKER + "# Configuration: " + clean_text(str(path)) + "\n"
            "[Desktop Entry]\nType=Application\nName=FICC Cluster Commander\n"
            "Comment=Start the local cluster service and open its console\n"
            "Exec=/usr/bin/env -- " + " ".join(map(desktop_quote, command)) + "\n"
            "Icon=" + icon + "\nTerminal=false\nCategories=System;Monitor;\nStartupNotify=false\n")
