# SPDX-License-Identifier: Apache-2.0
"""Manage the native macOS controller with a per-user launchd job."""

import os
import plistlib
import shlex
import subprocess
import time
from pathlib import Path

from . import launcher
from .launcher_config import NAME, LaunchConfig, load, read_private, save, write_file
from .launcher_runtime import executable
from .settings import private_directory


def label(config: LaunchConfig) -> str:
    return "org.ficc." + Path(config.unit_path).stem


def domain() -> str:
    return f"gui/{os.getuid()}"


def launchctl(*args: str, check: bool = True) -> subprocess.CompletedProcess:
    result = subprocess.run(["/bin/launchctl", *args], capture_output=True, text=True,
                            timeout=25, check=False)
    if check and result.returncode:
        raise ValueError("The macOS service request failed: " + result.stderr.strip()[:400])
    return result


def job(config: LaunchConfig, autostart: bool) -> dict:
    state = Path(config.state_dir)
    return {"Label": label(config), "ProgramArguments": config.command(),
            "RunAtLoad": autostart, "KeepAlive": False, "Umask": 0o077,
            "ExitTimeOut": 20, "ProcessType": "Interactive",
            "StandardOutPath": str(state / "service.log"),
            "StandardErrorPath": str(state / "service.log"),
            "EnvironmentVariables": {
                "PATH": "/opt/homebrew/opt/coreutils/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:"
                        "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
                "TMPDIR": str(state / "tmp"), "PYTHONNOUSERSITE": "1"}}


def verify(config: LaunchConfig) -> dict:
    if not config.unit_path.endswith(".plist"):
        raise ValueError("Install a macOS launcher for this configuration.")
    value = plistlib.loads(read_private(Path(config.unit_path)).encode())
    if type(value.get("RunAtLoad")) is not bool or value != job(config, value["RunAtLoad"]):
        raise ValueError("The installed launchd job differs from the FICC configuration.")
    current = launchctl("print", domain() + "/" + label(config), check=False)
    if current.returncode == 0 and f"path = {config.unit_path}\n" not in current.stdout:
        raise ValueError("Another launchd job uses this name. Select a different launcher name.")
    return value


def install(args, *, only_if_missing: bool = False) -> dict:
    if not NAME.fullmatch(args.name):
        raise ValueError("The launcher name must be ficc or ficc- followed by letters, digits or hyphens.")
    path = args.launcher_config.absolute()
    unit = Path.home() / "Library/LaunchAgents" / (args.name + ".plist")
    app_name = "FICC Cluster Commander" + (" " + args.name[5:] if args.name != "ficc" else "")
    app = Path.home() / "Applications" / (app_name + ".app")
    config = LaunchConfig(str(executable()), str(args.state_dir.absolute()), str(unit), str(app),
                          args.port, tuple(args.profile),
                          str(args.ssh_config.absolute()) if args.ssh_config else None, args.demo)
    private_directory(Path(config.state_dir))
    private_directory(Path(config.state_dir) / "tmp")
    with launcher.startup_lock(path):
        if path.exists() or path.is_symlink():
            old = load(path)
            if only_if_missing:
                return {"configuration": str(path), "existing": True}
            verify(old)
            if old.unit_path != config.unit_path or old.desktop_path != config.desktop_path:
                raise ValueError("Use a separate configuration file for a different launcher name.")
            if launchctl("print", domain() + "/" + label(old), check=False).returncode == 0:
                raise ValueError("Stop FICC before changing its launcher settings.")
        elif unit.exists() or unit.is_symlink() or app.exists() or app.is_symlink():
            raise ValueError("An existing startup file is not managed by this configuration.")
        if app.is_symlink():
            raise ValueError("The application bundle must not be a symbolic link.")
        write_file(unit, plistlib.dumps(job(config, args.autostart)).decode())
        script = "#!/bin/sh\n# Generated by FICC launcher.\nexec " + shlex.join(
            [config.executable, "launch", "--launcher-config", str(path)]) + "\n"
        write_file(app / "Contents/MacOS/ficc", script, 0o755)
        info = {"CFBundleIdentifier": label(config), "CFBundleName": app_name,
                "CFBundleDisplayName": app_name, "CFBundleExecutable": "ficc",
                "CFBundlePackageType": "APPL", "CFBundleVersion": "0.2.6",
                "LSUIElement": True}
        write_file(app / "Contents/Info.plist", plistlib.dumps(info).decode(), 0o644)
        save(path, config)
        verify(config)
    return {"configuration": str(path), "desktop_entry": str(app),
            "unit": label(config), "autostart": args.autostart}


def start(path: Path) -> LaunchConfig:
    path = path.absolute()
    with launcher.startup_lock(path):
        config = load(path)
        verify(config)
        if launcher.ready(config):
            return config
        target = domain() + "/" + label(config)
        if launchctl("print", target, check=False).returncode:
            launchctl("bootstrap", domain(), config.unit_path)
        launchctl("kickstart", target)
        deadline = time.monotonic() + 20
        while time.monotonic() < deadline:
            if launcher.ready(config):
                return config
            time.sleep(0.2)
        raise ValueError(f"FICC did not become ready. Inspect {config.state_dir}/service.log.")


def status(path: Path) -> dict:
    config = load(path.absolute())
    value = verify(config)
    ready = launcher.ready(config)
    return {"unit": label(config), "state": "running" if ready else "stopped",
            "ready": ready, "origin": f"http://127.0.0.1:{config.port}",
            "state_dir": config.state_dir, "autostart": value["RunAtLoad"]}


def stop(path: Path) -> dict:
    path = path.absolute()
    with launcher.startup_lock(path):
        config = load(path)
        verify(config)
        target = domain() + "/" + label(config)
        if launchctl("print", target, check=False).returncode == 0:
            launchctl("bootout", target)
        deadline = time.monotonic() + 25
        while Path(config.state_dir, "control.sock").exists():
            if time.monotonic() > deadline:
                raise ValueError("The controller has not stopped. Inspect its service.log before updating.")
            time.sleep(0.1)
    return {"unit": label(config), "stopped": True, "remote_jobs_cancelled": False}
