[build-system]
requires = ["setuptools==84.0.0", "wheel==0.48.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ficc-data-postgresql"
version = "0.2.5"
readme = "README.md"
description = "FICC postgresql data runtime provider."
requires-python = ">=3.12"
license = "Apache-2.0"
license-files = ["LICENSE"]
dependencies = ["psycopg[binary]==3.3.6"]

[project.entry-points."ficc.data"]
postgresql = "ficc_data_postgresql"

[tool.setuptools.packages.find]
where = ["src"]
